.travis.yml, LICENSE, README.md, flock.go, flock_example_test.go, flock_test.go
This is the initial commit of package `flock`, which provides a `sync.Locker` interface to file locking with the addition of a non-blocking `TryLock()` function.
The API documentation should be fairly filled-out, with an example provided in `flock_example_test.go` for the GoDoc documentation.
=> initial attempt at file locking in Go

flock.go, flock_test.go
This operation doesn't appear to be as atomic as I had hoped. It's causing some issues.
=> do not remove the file on Unlock()

.travis.yml
There have been some language changes since Go 1.5 that could cause valid Go
code to fail and compile, specifically if contexts were to be used.
This updates the TravisCI configuration to test against the two supported
versions of the Go runtime/toolkit.
=> Update TravisCI to test against the latest Go 1.9.x and 1.8.x

flock.go, flock_example_test.go, flock_test.go
This allows waiting for lock with timeout or other context cancel condition.
=> add .TryLockContext method to *Flock

flock.go, flock_test.go, flock_unix.go, flock_winapi.go, flock_windows.go
The Windows version is a guess, really. Also, you'll need to fix the path in the test file to point to your repo again.
=> Add shared lock support

flock_unix.go
I noticed that trying to obtain an exclusive lock on a file sitting on an NFS system did not work, and returned an error 'invalid file descriptor'. When debugging, I noticed that the `flock` command line tool was able to work without any errors, so I took a look at the source code.
https://github.com/karelzak/util-linux/blob/05541825553524e2ac353eb6c62c8b5ad049de24/sys-utils/flock.c#L294
The fix present there is to open the file in read+write mode, then try again.
=> Fix exclusive lock to work on Linux+NFS

flock.go
- Useful for long running processes that don't want to depend on the GC for cleanup
=> Add an explicit Close function

README.md
This is one of the final steps needed to complete the migration to the Gofrs
organization.
Signed-off-by: Tim Heckman <t@heckman.io>
=> Update README to replace references to theckman/go-flock

flock_unix.go
This is a trivial documentation typo fix.
=> Fix "ahred" -> "shared" typo in RLock documentation

.travis.yml, appveyor.yml
Noticed when looking over this project for https://github.com/gofrs/help-requests/issues/26
=> ci: use Go 1.10/1.11, test with -race

README.md, flock.go, flock_example_test.go, flock_test.go
=> Add New method and deprecate NewFlock

flock.go
(*Flock).Lock and (*Flock).Unlock return errors, unlike the Lock and
Unlock methods specified by sync.Locker. Therefore, don't mention
sync.Locker in package-level documentation, to avoid confusion.
Fixes #33.
=> don't mention sync.Locker in package documentation

README.md, flock.go
This should bring goreportcard to 100%. I've only changed function signatures in a private method, so this should be a non-breaking change.
=> Fix linting issues and add goreportcard badge

flock.go, flock_aix.go, flock_test.go, flock_unix.go
AIX doesn't provide a true flock() syscall. It does exist but it's just
a wrapper around fcntl. It doesn't provide safe locks under file
descriptors of a same process.
The current implementation is based on the file
cmd/go/internal/lockedfile/internal/filelock/filelock_fcntl.go.
Using fcntl implementation doesn't allow to have several RLocks at the
same time as closing a file descriptor might release the lock if even
others RLocks remain attached.
=> Add AIX support with fcntl

flock_aix.go
Closes #51 
Fix an issue where the AIX implementation uses F_SETLKW instead of F_SETLK for `TryLock()`. This causes `TryLock()` to wait indefinitely for a lock instead of returning with failure. See [fcntl() Documentation](https://github.com/gofrs/flock)
I could not figure a way to reproduce this issue with a Unit test. New go-routine did not trigger it, and spawning a separate process became messy real quick. I tested by hand both `Lock()` and `TryLock()` variants between two separate processes and it worked as expected.
Unit tests continue run pass successfully under AIX.
=> Fix issue caused by calling F_SETLKW instead of F_SETLK

README.md
The interface `sync.Locker` is:
```go
type Locker interface {
Lock()
Unlock()
}
```
https://github.com/golang/go/blob/5a18e79687dea15680ff5f799b549fa0efd0cad9/src/sync/mutex.go#L41-L45
But the method signatures of `Flock` are:
```go
type Foo interface {
Lock() error
Unlock() error
}
```
So to implement `sync.Locker` interface, a wrapper should be used.
Example:
```go
type Wrapper struct {
f *Flock
}
func NewWrapper(path string) *Wrapper {
return &Wrapper{f: flock.New(path)}
}
func (w Wrapper) Lock() {
err := w.f.Lock()
if err != nil {
panic(err)
}
}
func (w Wrapper) Unlock() {
err := w.f.Unlock()
if err != nil {
panic(err)
}
}
```
Fixes #45
=> docs: remove reference to sync.Locker

.golangci.yml
I fixed the problem with `Syscall6` inside 407d4adcd8fed6f3fb745b6b83d93608972435b1 (I wrongly named the commit)
=> chore(ci): remove Syscall6 deprecation exclusion

build.sh, flock.go, flock_test.go, flock_unix.go, flock_unix_variants.go
Solaris/Illumos/SmartOS have basically the same issue as AIX. Consolidated use for both.
Related to #60
=> feat: add support for Illumos/Solaris

flock.go
To avoid breaking changes (constructor signature and existing behavior), I extended the current constructor with a variadic of functions to add options.
The approach avoids creating a new constructor, like `NewWithOptions(path string, opts Options)`, and breaking the current constructor signature.
```go
func New(path string, opts ...Option) *Flock {
...
}
```
There are 2 options:
- `SetFlag`: sets the flag used to create/open the file.
- `SetPermissions`: sets the OS permissions to set on the file.
```go
_ = flock.New("example", flock.SetFlag(os.O_CREATE|os.O_RDWR)))
_ = flock.New("example", flock.SetPermissions(os.FileMode(0o600)))
_ = flock.New("example", flock.SetFlag(os.O_CREATE|os.O_RDWR), flock.SetPermissions(os.FileMode(0o600)))
```
Fixes #59
=> feat: add option to define flag and permissions of the file

flock.go, flock_internal_test.go, flock_test.go, flock_windows.go
Replaces `os.TempDir()` by `t.TempDir()` to remove the files generated during tests.
=> tests: remove files generated during tests

flock.go, flock_unix_fcntl.go
`os.FileMode` and `os.PathError` are aliases on `fs.FileMode` and `fs.PathError`.
=> chore: replace os.(FileMode,PathError) by fs.(...)

flock_unix_fcntl.go
=> fix: update fnctl implementation

build.sh, flock_example_test.go, flock_internal_test.go, flock_others.go, flock_test.go, flock_unix.go, flock_windows.go
Instead of being blocked on unsupported platforms (`*/wasm` and `plan9/*`), `flock` will throught runtime errors.
The errors are:
```go
return &fs.PathError{
Op:   "RLock",
Path: f.Path(),
Err:  errors.ErrUnsupported,
}
```
The implementation for unsupported platforms can be added in the future.
Fixes #60
=> feat: use runtime errors instead of compilation errors for unusupported platforms

flock_unix.go, flock_unix_fcntl.go, flock_windows.go
https://github.com/gofrs/flock/pull/86#issuecomment-2204330340
=> refactor: use x/sys/* instead of Syscall when possible

flock_internal_test.go, flock_test.go
Since the addition of options to define the flag, a directory can be used as a path for the lock.
This doesn't work on Windows.
This has not been tested on AIX, Solaris. 
Closes #49
=> tests: add tests about directory support

flock.go, flock_unix.go, flock_unix_fcntl.go, flock_windows.go
relates to https://github.com/docker/buildx/issues/2593
seems a regression introduced in https://github.com/gofrs/flock/commit/b659e1e00ac3f430ee58fbfc49f69a9a3b45178c that removes read-write flag: https://github.com/gofrs/flock/commit/b659e1e00ac3f430ee58fbfc49f69a9a3b45178c#diff-87c2c4fe0fb43f4b38b4bee45c1b54cfb694c61e311f93b369caa44f6c1323ffR192
cc @ldez
=> fix: missing read-write flag in reopenFDOnError
